swagger: "2.0"
info:
  description: "this is a api for authenticating users and binding cloud accounts."
  version: "1.0.0"
  title: "Auth api"

host: "52.82.26.240:5000"

paths:
  /authenticate:
    post:
      tags:
      - "auth"
      summary: "Get a accessToken"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        description: "account of fastone"
        required: true
        in: "body"
        schema:
          $ref: "#/definitions/Auth"
      responses:
        400:
          description: "Invalid input"
        403:
          description: "Invalid credential"
        200:
          description: "Get a accessToken"
  /accounts/{usernameOrEmail}:
    get:
      tags:
      - "accounts"
      summary: "Finds all information by usernameOrEmail"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "accessToken"
        in: "header"
        required: true
        type: "string"
      - name: "usernameOrEmail"
        in: "path"
        description: "account of user that needs to be finded"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Invalid input"
        405:
          description: "Validation exception"


